-- ========================================================
-- Real-Time Fund (基估宝) - Supabase Schema
-- ========================================================


-- ========================================================
-- 1. 用户配置表 (user_configs)
-- 用于云端同步用户的所有本地数据
-- ========================================================

CREATE TABLE public.user_configs (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  data json null,
  updated_at timestamp with time zone null,
  user_id uuid not null,
  last_device_id text null, -- 1.3.5 新增
  ytd_return_rate numeric null, -- 2.2.0 新增
  CONSTRAINT user_configs_pkey PRIMARY KEY (id),
  CONSTRAINT user_configs_user_id_key UNIQUE (user_id)
) TABLESPACE pg_default;

CREATE INDEX idx_user_configs_ytd_return_rate ON public.user_configs (ytd_return_rate);

-- 启用行级安全（RLS）
ALTER TABLE public.user_configs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "user_configs_select_own" ON public.user_configs;
DROP POLICY IF EXISTS "user_configs_insert_own" ON public.user_configs;
DROP POLICY IF EXISTS "user_configs_update_own" ON public.user_configs;

CREATE POLICY "user_configs_select_own"
ON public.user_configs
FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "user_configs_insert_own"
ON public.user_configs
FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "user_configs_update_own"
ON public.user_configs
FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- --------------------------------------------------------
-- 全量更新函数 (update_user_config_full)
-- --------------------------------------------------------
CREATE OR REPLACE FUNCTION public.update_user_config_full(payload jsonb, p_last_device_id text default null, p_force_takeover boolean default false)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS
$$
declare
  current_device_id text;
  v_ytd_rate numeric := null;
begin
  select last_device_id into current_device_id from public.user_configs where user_id = auth.uid();

  if current_device_id is not null and p_last_device_id is not null and current_device_id != p_last_device_id and not p_force_takeover then
    raise exception 'DEVICE_CONFLICT: Logged in on another device';
  end if;

  if payload ? 'ytdReturnRate' then
    v_ytd_rate := (payload->>'ytdReturnRate')::numeric;
  end if;

  insert into public.user_configs (user_id, data, updated_at, last_device_id, ytd_return_rate)
  values (auth.uid(), payload::json, now(), p_last_device_id, v_ytd_rate)
  on conflict (user_id) do update
  set data = excluded.data,
      updated_at = excluded.updated_at,
      last_device_id = coalesce(excluded.last_device_id, public.user_configs.last_device_id),
      ytd_return_rate = coalesce(v_ytd_rate, public.user_configs.ytd_return_rate);
end;
$$;

REVOKE ALL ON FUNCTION public.update_user_config_full(jsonb, text, boolean) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.update_user_config_full(jsonb, text, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_user_config_full(jsonb, text, boolean) TO service_role;

-- --------------------------------------------------------
-- 增量更新函数 (update_user_config_partial)
-- --------------------------------------------------------
CREATE OR REPLACE FUNCTION public.update_user_config_partial(payload jsonb, p_last_device_id text default null, p_force_takeover boolean default false)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS
$$
declare
  current_device_id text;
  v_ytd_rate numeric := null;
begin
  select last_device_id into current_device_id from public.user_configs where user_id = auth.uid();

  if current_device_id is not null and p_last_device_id is not null and current_device_id != p_last_device_id and not p_force_takeover then
    raise exception 'DEVICE_CONFLICT: Logged in on another device';
  end if;

  if payload ? 'ytdReturnRate' then
    v_ytd_rate := (payload->>'ytdReturnRate')::numeric;
  end if;

  update public.user_configs
  set data = ((coalesce(data::jsonb, '{}'::jsonb) || payload)::json),
      updated_at = now(),
      last_device_id = coalesce(p_last_device_id, last_device_id),
      ytd_return_rate = coalesce(v_ytd_rate, ytd_return_rate)
  where user_id = auth.uid();
end;
$$;

-- --------------------------------------------------------
-- 获取 YTD 击败用户比例 (get_ytd_percentile)
-- --------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_ytd_percentile(p_ytd_rate numeric)
RETURNS numeric
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  total_count int;
  beat_count int;
BEGIN
  SELECT count(*) INTO total_count FROM public.user_configs WHERE user_id <> auth.uid() AND ytd_return_rate IS NOT NULL;
  IF total_count < 10 THEN
    RETURN -1; -- Returns -1 to indicate insufficient data
  END IF;
  SELECT count(*) INTO beat_count
  FROM public.user_configs
  WHERE user_id <> auth.uid() AND ytd_return_rate IS NOT NULL AND ytd_return_rate < p_ytd_rate;
  RETURN round((beat_count::numeric / total_count::numeric) * 100, 2);
END;
$$;

REVOKE ALL ON FUNCTION public.get_ytd_percentile(numeric) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_ytd_percentile(numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_ytd_percentile(numeric) TO service_role;

REVOKE ALL ON FUNCTION public.update_user_config_partial(jsonb, text, boolean) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.update_user_config_partial(jsonb, text, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_user_config_partial(jsonb, text, boolean) TO service_role;


-- ========================================================
-- 1.1 基金守望提醒发送记录
-- 记录某天某类报告是否已发送，并保存不含金额的公开信息摘要供网页展示
-- ========================================================

CREATE TABLE IF NOT EXISTS public.fund_watch_reports (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  report_date date not null,
  report_mode text not null check (report_mode in ('preclose', 'evening')),
  report_data jsonb null,
  sent_at timestamp with time zone not null default now(),
  CONSTRAINT fund_watch_reports_pkey PRIMARY KEY (id),
  CONSTRAINT fund_watch_reports_user_date_mode_key UNIQUE (user_id, report_date, report_mode)
) TABLESPACE pg_default;

-- 兼容已经创建过旧版 fund_watch_reports 表的个人项目
ALTER TABLE public.fund_watch_reports
ADD COLUMN IF NOT EXISTS report_data jsonb null;

ALTER TABLE public.fund_watch_reports ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "fund_watch_reports_select_own" ON public.fund_watch_reports;

CREATE POLICY "fund_watch_reports_select_own"
ON public.fund_watch_reports
FOR SELECT
USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_fund_watch_reports_user_date
ON public.fund_watch_reports (user_id, report_date desc);


-- ========================================================
-- 2. 基金板块数据
-- 包含: fund_related, fund_secid, fund_topic
-- ========================================================

-- --------------------------------------------------------
-- 关联板块表 (fund_related)
-- --------------------------------------------------------
CREATE TABLE public.fund_related (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  fund_code character varying null,
  related_sector text null,
  CONSTRAINT fund_related_pkey PRIMARY KEY (id),
  CONSTRAINT fund_related_fund_code_key UNIQUE (fund_code)
) TABLESPACE pg_default;

ALTER TABLE public.fund_related ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated users to select fund_related"
ON public.fund_related
FOR SELECT
TO authenticated
USING (auth.uid() IS NOT NULL);

-- --------------------------------------------------------
-- 基金 SecId 表 (fund_secid)
-- --------------------------------------------------------
CREATE TABLE public.fund_secid (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  related_sector text null,
  secid character varying null,
  CONSTRAINT fund_secid_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

ALTER TABLE public.fund_secid ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated users to select fund_secid"
ON public.fund_secid
FOR SELECT
TO authenticated
USING (auth.uid() IS NOT NULL);

-- --------------------------------------------------------
-- 基金主题表 (fund_topic)
-- --------------------------------------------------------
CREATE TABLE public.fund_topic (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  update_at timestamp with time zone null,
  sector_type text null,
  sector_id text null,
  sector_name text null,
  update_frequency text null,
  net_inflow bigint null,
  change_pct real null,
  CONSTRAINT fund_topic_pkey PRIMARY KEY (id),
  CONSTRAINT fund_topic_sector_id_key UNIQUE (sector_id),
  CONSTRAINT fund_topic_sector_name_key UNIQUE (sector_name)
);

ALTER TABLE public.fund_topic ENABLE ROW LEVEL SECURITY;

CREATE POLICY "允许已登录用户读取基金主题数据"
ON public.fund_topic
FOR SELECT
TO authenticated
USING (true);


-- ========================================================
-- 3. 限制流与审计记录
-- ========================================================

-- --------------------------------------------------------
-- OCR 每日调用次数限流表 (ocr_daily_usage)
-- --------------------------------------------------------
CREATE TABLE public.ocr_daily_usage (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  usage_date date not null default current_date,
  count int not null default 0,
  CONSTRAINT ocr_daily_usage_pkey PRIMARY KEY (id),
  CONSTRAINT ocr_daily_usage_unique UNIQUE (user_id, usage_date)
) TABLESPACE pg_default;

-- 索引加速查询
CREATE INDEX idx_ocr_daily_usage_user_date ON public.ocr_daily_usage (user_id, usage_date);

ALTER TABLE public.ocr_daily_usage ENABLE ROW LEVEL SECURITY;

-- 允许已登录用户查看自己的用量
CREATE POLICY "ocr_usage_select_own"
ON public.ocr_daily_usage
FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

-- --------------------------------------------------------
-- 原子检查并自增 OCR 用量的函数 (check_and_increment_ocr_usage)
-- 返回: { allowed: boolean, current_count: int, max_limit: int }
-- --------------------------------------------------------
CREATE OR REPLACE FUNCTION public.check_and_increment_ocr_usage(
  p_max_limit int default 10
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS
$$
declare
  v_user_id uuid := auth.uid();
  v_today date := current_date;
  v_current_count int;
begin
  if v_user_id is null then
    return jsonb_build_object('allowed', false, 'current_count', 0, 'max_limit', p_max_limit, 'error', 'NOT_AUTHENTICATED');
  end if;

  -- 尝试 upsert 并原子自增
  insert into public.ocr_daily_usage (user_id, usage_date, count)
  values (v_user_id, v_today, 1)
  on conflict (user_id, usage_date)
  do update set count = ocr_daily_usage.count + 1
  where ocr_daily_usage.count < p_max_limit
  returning count into v_current_count;

  -- 如果没有 returning 结果，说明已达上限（WHERE 条件不满足）
  if v_current_count is null then
    select count into v_current_count
    from public.ocr_daily_usage
    where user_id = v_user_id and usage_date = v_today;

    return jsonb_build_object('allowed', false, 'current_count', coalesce(v_current_count, 0), 'max_limit', p_max_limit);
  end if;

  return jsonb_build_object('allowed', true, 'current_count', v_current_count, 'max_limit', p_max_limit);
end;
$$;

REVOKE ALL ON FUNCTION public.check_and_increment_ocr_usage(int) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.check_and_increment_ocr_usage(int) TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_and_increment_ocr_usage(int) TO service_role;
